# Generated by Django 4.2.18 on 2025-02-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0002_entries_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
