# Generated by Django 4.2.18 on 2025-02-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0004_alter_entries_name_alter_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='entries_image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
