# Generated by Django 4.2.18 on 2025-02-27 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0005_alter_entries_entries_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('entries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cms_app.entries')),
            ],
        ),
    ]
