# Generated by Django 4.2.18 on 2025-02-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0007_rename_created_date_comment_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='rashmika', max_length=255),
            preserve_default=False,
        ),
    ]
