# Generated by Django 4.2.18 on 2025-02-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0009_rename_comment_comment_entries_remove_comment_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(default='nice', max_length=1000),
            preserve_default=False,
        ),
    ]
